services:
  frontend:
    build: ./bobbin_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./bobbin_frontend:/app
    command: sh -c "npm run dev"
    environment:
      - NODE_ENV=development

  api:
    build: ./bobbin_api
    ports:
      - "3001:3001"
    volumes:
      - ./bobbin_api:/app
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    environment:
      - RAILS_ENV=development
      - DATABASE_PASSWORD=bobbin
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - bobbin_db:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bobbin_development
      - MYSQL_USER=bobbin
      - MYSQL_PASSWORD=bobbin

volumes:
  bobbin_db: